FROM node:20-alpine3.17

WORKDIR /usr/src/app
COPY package*.json ./

# for production
RUN npm ci --omit=dev
ENV NODE_ENV production

# for development
# RUN npm install

COPY . .

EXPOSE 8080
CMD ["node", "index.js"]
