FROM node:20-alpine3.17

WORKDIR /usr/src/app
COPY package*.json ./

# for production
RUN npm ci --omit=dev
ENV NODE_ENV production

# for development
# RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000
CMD ["npm", "serve", "build"]
